spring:
  application:
    name:  ${SPRING_APPLICATION_NAME:vecure-discovery-service}
  security:
    basic.enabled: true
    user:
      name: ${EUREKA_USERNAME:admin}
      password: ${EUREKA_PASSWORD:password}
  cloud:
    discovery:
      enabled: true
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/ # URL for Eureka Server
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # Eureka server URL
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true # Optional: Use the IP address for the instance instead of hostname
    lease-expiration-duration-in-seconds: 10 # Optional: How long to wait before considering the instance expired
    lease-renewal-interval-in-seconds: 5 # Optional: How often the instance renews its lease
server:
  port: 8761
  error.whitelabel.enabled: false
  http2.enabled: ${HTTP2_ENABLE:true}
  
logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.web.client: DEBUG  # For logging HTTP requests/responses
      
management:
  endpoints:
    web:
      exposure:
        include: "*"